# Generated by Django 2.1.5 on 2019-02-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='contnet',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
    ]
